### ISSUE TITLE
Javalang don't support Java8 `default` keyword.

### ISSUE THREAD

**Issue by roipoussiere** [c2nes/javalang#29]
Let this simple Java8 code:

    public interface Test{ default void save() {} }

which works according to javac:

    echo "public interface Test{ default void save() {} }" > Test.java
    javac Test.java

But javalang throws a Syntax error. Here working in a clean virtual env., tested both with Py2 and Py3:

```
import javalang
tree = javalang.parse.parse("package javalang.brewtab.com; public interface Test{ default void save() {} }")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/roipoussiere/.local/lib/python2.7/site-packages/javalang/parse.py", line 53, in parse
    return parser.parse()
  File "/home/roipoussiere/.local/lib/python2.7/site-packages/javalang/parser.py", line 110, in parse
    return self.parse_compilation_unit()
  File "/home/roipoussiere/.local/lib/python2.7/site-packages/javalang/parser.py", line 296, in parse_compilation_unit
    type_declaration = self.parse_type_declaration()
  File "/home/roipoussiere/.local/lib/python2.7/site-packages/javalang/parser.py", line 341, in parse_type_declaration
    return self.parse_class_or_interface_declaration()
  File "/home/roipoussiere/.local/lib/python2.7/site-packages/javalang/parser.py", line 354, in parse_class_or_interface_declaration
    type_declaration = self.parse_normal_interface_declaration()
  File "/home/roipoussiere/.local/lib/python2.7/site-packages/javalang/parser.py", line 429, in parse_normal_interface_declaration
    body = self.parse_interface_body()
  File "/home/roipoussiere/.local/lib/python2.7/site-packages/javalang/parser.py", line 945, in parse_interface_body
    declaration = self.parse_interface_body_declaration()
  File "/home/roipoussiere/.local/lib/python2.7/site-packages/javalang/parser.py", line 960, in parse_interface_body_declaration
    declaration = self.parse_interface_member_declaration()
  File "/home/roipoussiere/.local/lib/python2.7/site-packages/javalang/parser.py", line 986, in parse_interface_member_declaration
    declaration = self.parse_interface_method_or_field_declaration()
  File "/home/roipoussiere/.local/lib/python2.7/site-packages/javalang/parser.py", line 992, in parse_interface_method_or_field_declaration
    java_type = self.parse_type()
  File "/home/roipoussiere/.local/lib/python2.7/site-packages/javalang/parser.py", line 461, in parse_type
    self.illegal("Expected type")
  File "/home/roipoussiere/.local/lib/python2.7/site-packages/javalang/parser.py", line 119, in illegal
    raise JavaSyntaxError(description, at)
javalang.parser.JavaSyntaxError
```

It seems that [this set](https://github.com/c2nes/javalang/blob/6d3e65e202f9df9a0819a19cf6d51587bd37eac5/javalang/tokenizer.py#L33) and [this one](https://github.com/c2nes/javalang/blob/6d3e65e202f9df9a0819a19cf6d51587bd37eac5/javalang/tokenizer.py#L45) should contains `'default'` to support Java8.

**Comment by c2nes** [comment]
Thanks @roipoussiere, just pushed up a fix to master

**Comment by roipoussiere** [comment]
Thank you for this quick fix!

**Comment by roipoussiere** [comment]
Well, not really fixed. :-)
