### ISSUE TITLE
解析lang包里的System.java会出现错误

### ISSUE THREAD

**Issue by liepengGitHub** [c2nes/javalang#78]
Traceback (most recent call last):
  File "E:\STDR\python\lib\site-packages\javalang\parser.py", line 1303, in parse_block_statement
    return self.parse_local_variable_declaration_statement()
  File "E:\STDR\python\lib\site-packages\javalang\parser.py", line 1311, in parse_local_variable_declaration_statement
    declarators = self.parse_variable_declarators()
  File "E:\STDR\python\lib\site-packages\javalang\parser.py", line 1166, in parse_variable_declarators
    declarator = self.parse_variable_declarator()
  File "E:\STDR\python\lib\site-packages\javalang\parser.py", line 1176, in parse_variable_declarator
    identifier = self.parse_identifier()
  File "E:\STDR\python\lib\site-packages\javalang\parser.py", line 233, in parse_identifier
    return self.accept(Identifier)
  File "E:\STDR\python\lib\site-packages\javalang\parser.py", line 136, in accept
    self.illegal("Expected %s" % (accept.__name__,))
  File "E:\STDR\python\lib\site-packages\javalang\parser.py", line 122, in illegal
    raise JavaSyntaxError(description, at)
javalang.parser.JavaSyntaxError

**Comment by lyriccoder** [comment]
Could you please provide the example of Java class? Seems you have a syntax error in your Java class
